import os
import re
import math
from groq import Groq

# =====================================================================
# SIGNAL 1: LLM-Based Attribution Analysis
# =====================================================================
def analyze_llm_attribution(text: str) -> float:
    """
    Evaluates text pattern predictability utilizing a cloud-hosted LLM.
    Returns a float calibrated between 0.0 and 1.0.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError("Critical System Error: 'GROQ_API_KEY' environment variable missing.")

    client = Groq(api_key=api_key)

    system_prompt = (
        "You are a forensic linguistic analysis engine. Analyze the following text "
        "and determine the mathematical probability that it was generated by an LLM "
        "versus a human author. Respond with exactly one floating-point number between "
        "0.00 and 1.00, where 0.00 represents completely human-written and 1.00 represents "
        "completely machine-generated. Do not include any introductory words, markdown formatting, "
        "explanations, or punctuation. Output only the numeric value."
    )

    try:
        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text}
            ],
            temperature=0.1,
            max_tokens=10
        )
        raw_response = completion.choices[0].message.content.strip()
        return float(raw_response)
    except Exception:
        # Fallback safe structural default default if API drops connection
        return 0.50


# =====================================================================
# SIGNAL 2: Stylometric Heuristics (Pure Python NLP)
# =====================================================================
def analyze_stylometric_heuristics(text: str) -> float:
    """
    Calculates vocabulary diversity and sentence length variation algorithms.
    Returns a normalized structural score between 0.0 (Human) and 1.0 (AI).
    """
    # 1. Standard cleaning and text parsing
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = [w.lower() for w in re.findall(r'\b\w+\b', text)]
    
    if not words or not sentences:
        return 0.50 # Return inconclusive neutral score for empty/tiny inputs

    # --- Metric A: Lexical Diversity (Type-Token Ratio) ---
    # Humans use rich vocabulary; AI reuses safe words repeatedly.
    total_words = len(words)
    unique_words = len(set(words))
    ttr = unique_words / total_words

    # --- Metric B: Sentence Length Variation (Burstiness) ---
    # AI writes regular, uniform length sentences. Humans write erratically.
    sentence_lengths = [len(s.split()) for s in sentences]
    num_sentences = len(sentence_lengths)
    
    if num_sentences > 1:
        mean_length = sum(sentence_lengths) / num_sentences
        variance = sum((x - mean_length) ** 2 for x in sentence_lengths) / num_sentences
        std_deviation = math.sqrt(variance)
    else:
        std_deviation = 0.0  # Single sentence means zero structural variation

    # --- Normalization & Calibration Layer ---
    # Convert metric data points to a standard [0.0 - 1.0] scale where 1.0 is highly AI-like
    
    # 1. High Lexical Diversity (TTR close to 1) -> More human-like (0.0)
    #    Low Lexical Diversity (TTR close to 0) -> More machine-like (1.0)
    lexical_ai_score = 1.0 - ttr

    # 2. High Sentence Deviation (Burstiness) -> More human-like (0.0)
    #    Low Sentence Deviation (Uniform lengths) -> More machine-like (1.0)
    #    We map standard deviation to an activation window (0 to 15+ words variation)
    if std_deviation >= 15.0:
        variation_ai_score = 0.0
    else:
        variation_ai_score = 1.0 - (std_deviation / 15.0)

    # Combine both local stylometric metrics equally to get the Signal 2 score
    stylometric_score = (lexical_ai_score + variation_ai_score) / 2.0
    return round(max(0.0, min(1.0, stylometric_score)), 2)


# =====================================================================
# SYSTEM COMBINATION ENGINE
# =====================================================================
def calculate_combined_confidence(llm_score: float, stylometric_score: float, word_count: int = None) -> float:
    """
    Applies the specified design contract formula weights:
    65% LLM-Based Analysis + 35% Stylometric Heuristics.

    For short inputs (under 50 words) the stylometric heuristics become unreliable
    (TTR is mechanically high and there are too few sentences to measure burstiness),
    so we shift the weighting toward the LLM signal to avoid an artificially
    "human-like" stylometric score dragging clearly-AI text into the uncertain band.
    To avoid a sudden jump at the 50-word boundary, the semantic weight is scaled
    smoothly from 0.85 (at 10 words) down to 0.65 (at 50 words).
    """
    # Short-text weighting adjustment (disabled): flat 65/35 weighting is used for all texts.
    # if word_count is not None and word_count < 50:
    #     # Linearly interpolate the semantic weight from 0.85 (10 words) to 0.65 (50 words)
    #     llm_weight = max(0.65, 0.85 - ((word_count - 10) / 40) * 0.20)
    #     stylometric_weight = 1.0 - llm_weight
    # else:
    #     llm_weight, stylometric_weight = 0.65, 0.35
    llm_weight, stylometric_weight = 0.65, 0.35

    final_score = (llm_weight * llm_score) + (stylometric_weight * stylometric_score)
    return round(max(0.0, min(1.0, final_score)), 2)

# =====================================================================
# TRANSPARENCY LABEL GENERATION ENGINE
# =====================================================================
def _confidence_phrase(confidence_percent: int) -> str:
    """
    Maps a confidence percentage to a qualitative strength phrase so the label text
    visibly changes with the confidence level, not just the displayed number.
    """
    if confidence_percent >= 85:
        return "high confidence"
    elif confidence_percent >= 70:
        return "moderate confidence"
    else:
        return "low confidence"


def generate_transparency_label(final_score: float) -> dict:
    """
    Maps the final combined score into a specific user-facing label classification
    and dynamically re-calibrates the confidence text matrix.
    """
    if final_score >= 0.70:
        confidence_percent = int(final_score * 100)
        attribution = "likely_ai"
        text = (
            f"Likely AI > Our system has {_confidence_phrase(confidence_percent)} ({confidence_percent}%) "
            f"that this text matches patterns consistent with AI-generated writing."
        )
    elif final_score <= 0.40:
        # Confidence calculation: confidence = 1.0 - final_score
        confidence_percent = int((1.0 - final_score) * 100)
        attribution = "likely_human"
        text = (
            f"Likely Human > Our system has {_confidence_phrase(confidence_percent)} ({confidence_percent}%) "
            f"that this text exhibits patterns consistent with original human writing."
        )
    else:
        attribution = "uncertain"
        text = (
            "Uncertain > Our system detected a mix of original and automated "
            "writing patterns. We cannot definitively determine authorship for this submission."
        )

    return {
        "attribution": attribution,
        "label": text
    }